#!/bin/sh
# this is /etc/cron.daily/checkrealserver.cron, chmod 0750
email=error.notify@keeptherecords.com
progname=mda-server

for ((a=1; a <= 58 ; a++))
do

    if [ "$(pidof $progname)" = "" ]
    then nohup /keep-the-records/mda-server /keep-the-records/ktr-db &
    fi
    sleep 1
done
		# echo "rmserver found down on $(date +%m-%d-%Y)" | mail -s "$progname on $(hostname) down at $(date)" $email; fi