#!/bin/bash

source /etc/profile

#email=error.notify@keeptherecords.com
progname=mda-server

for ((a=1; a <= 58 ; a++))
do

    if [ "$(pidof $progname)" = "" ]
    then nohup ~/mda/mda-server ~/keep-the-records/ktr-db -:h50000000 &
    fi
    sleep 1
done
		# echo "rmserver found down on $(date +%m-%d-%Y)" | mail -s "$progname on $(hostname) down at $(date)" $email; fi
