#!/bin/bash

source /etc/profile
source ~/.bashrc

nohup ktr-awful --port=12000 ~/keep-the-records &
nohup ktr-awful --port=12001 ~/keep-the-records &
nohup ktr-awful --port=12002 ~/keep-the-records &
nohup ktr-awful --port=12003 ~/keep-the-records &