#!/bin/bash

#rsync -aurtvv --exclude 'essays-in' --exclude 'nohup.out' --exclude 'ktr-db.dir' --exclude 'ktr-db.pag' -e ssh . webaccess@staging.keeptherecords.com:/keep-the-records | grep -v 'uptodate'

#rsync -naurtvv --exclude '.git' --exclude 'essays-in' --exclude 'nohup.out' --exclude 'ktr-db' -e ssh . webaccess@thintz.com:/keep-the-records | grep -v 'uptodate'

echo "continue? "

read cont

if [(read) == 'y']; then
    echo "hi"
    #rsync -aurtvv --exclude '.git' --exclude 'essays-in' --exclude 'nohup.out' --exclude 'ktr-db' -e ssh . webaccess@thintz.com:/keep-the-records | grep -v 'uptodate'
fi