`("Awana Data" (("Puggles" (("none" (("none" ("none"))))))
                ("Cubbies" (("Hopper" (("Bear Hug Brochure" ("1" "2"))
				       ("Hopper Trail" ("1" "2"))
				       ("Lamb Path 1" ("1" "2"))
				       ("Elephant Walk 1" ("1" "2"))
				       ("Lamb Path 2" ,(srange 1 4))
				       ("Elephant Walk 2" ,(srange 1 4))
				       ("Lamb Path 3" ,(srange 1 4))
				       ("Elephant Walk 3" ,(srange 1 4))
				       ("Lamb Path 4" ,(srange 1 4))
				       ("Elephant Walk 4" ,(srange 1 4))
				       ("Under the Apple Tree" ,(srange 1 25))
				       ("Character Builder" ,(srange 1 21))
				       ("Special Hugs" ,(srange 1 7))))
			    ("Jumper" (("Bear Hug Brochure" ("1" "2"))
				       ("Jumper Trail" ("1" "2"))
				       ("Lamb Path 1" ("1" "2"))
				       ("Elephant Walk 1" ("1" "2"))
				       ("Lamb Path 2" ,(srange 1 4))
				       ("Elephant Walk 2" ,(srange 1 4))
				       ("Lamb Path 3" ,(srange 1 4))
				       ("Elephant Walk 3" ,(srange 1 4))
				       ("Lamb Path 4" ,(srange 1 4))
				       ("Elephant Walk 4" ,(srange 1 4))
				       ("Under the Apple Tree" ,(srange 1 25))
				       ("Character Builder" ,(srange 1 21))
				       ("Special Hugs" ,(srange 1 7))))))
		("Sparks" (("Flight 3:16" (("Flight 3:16" ,(srange 1 7))))
			   ("HangGlider" (("HangGlider Rank" ,(srange 1 9))
					  ("Red Jewel 1" ,(srange 1 5))
					  ("Green Jewel 1" ,(srange 1 5))
					  ("Red Jewel 2" ,(srange 1 5))
					  ("Green Jewel 2" ,(srange 1 5))
					  ("Red Jewel 3" ,(srange 1 5))
					  ("Green Jewel 3" ,(srange 1 5))
					  ("Red Jewel 4" ,(srange 1 5))
					  ("Green Jewel 4" ,(srange 1 5))
					  ("Review HangGlider Rank" ("1" "3" "4" "5" "6" "7"))
					  ("Review Red Jewel 1" ("2" "3" "4"))
					  ("Review Green Jewel 1" ("2" "3" "4"))
					  ("Review Red Jewel 2" ("2" "3" "4"))
					  ("Review Green Jewel 2" ("4"))
					  ("Review Green Jewel 3" ("1"))
					  ("Review Red Jewel 4" ("2" "3" "4"))
					  ("Review Green Jewel 4" ("2"))
					  ("Return Flight" ,(srange 1 16))
					  ("Takeoff" ,(srange 1 6))
					  ("Passport" ,(srange 1 6))
					  ("Passenger List" ,(srange 1 6))
					  ("Landing Gear" ,(srange 1 6))))
			    ("WingRunner" (("WingRunner Rank" ,(srange 1 9))
					   ("Red Jewel 1" ,(srange 1 5))
					   ("Green Jewel 1" ,(srange 1 5))
					   ("Red Jewel 2" ,(srange 1 5))
					   ("Green Jewel 2" ,(srange 1 5))
					   ("Red Jewel 3" ,(srange 1 5))
					   ("Green Jewel 3" ,(srange 1 5))
					   ("Red Jewel 4" ,(srange 1 5))
					   ("Green Jewel 4" ,(srange 1 5))
					   ("Review WingRunner Rank" ,(append (srange 1 7)) '("8"))
					   ("Review Red Jewel 1" ("2" "3" "4"))
					   ("Review Green Jewel 1" ("1" "2" "3"))
					   ("Review Red Jewel 2" ("3"))
					   ("Review Green Jewel 2" ("3" "4"))
					   ("Review Green Jewel 3" ("4"))
					   ("Review Red Jewel 4" ,(srange 1 5))
					   ("Review Green Jewel 4" ("1" "2"))
					   ("Return Flight" ,(srange 1 16))
					   ("Takeoff" ,(srange 1 6))
					   ("Passport" ,(srange 1 6))
					   ("Passenger List" ,(srange 1 6))
					   ("Landing Gear" ,(srange 1 6))))
			    ("SkyStormer" (("SkyStormer Rank" ,(srange 1 9))
					   ("Red Jewel 1" ,(srange 1 5))
					   ("Green Jewel 1" ,(srange 1 5))
					   ("Red Jewel 2" ,(srange 1 5))
					   ("Green Jewel 2" ,(srange 1 5))
					   ("Red Jewel 3" ,(srange 1 5))
					   ("Green Jewel 3" ,(srange 1 5))
					   ("Red Jewel 4" ,(srange 1 5))
					   ("Green Jewel 4" ,(srange 1 5))
					   ("Review SkyStormer Rank" ,(srange 1 8))
					   ("Review Red Jewel 1" ,(srange 1 5))
					   ("Review Green Jewel 1" ,(srange 1 5))
					   ("Review Red Jewel 2" ,(srange 1 5))
					   ("Review Green Jewel 2" ,(srange 1 5))
					   ("Review Red Jewel 3" ,(srange 1 5))
					   ("Review Green Jewel 3" ,(srange 1 5))
					   ("Review Red Jewel 4" ,(srange 1 5))
					   ("Review Green Jewel 4" ,(srange 1 5))
					   ("Return Flight" ,(srange 1 16))
					   ("Takeoff" ,(srange 1 6))
					   ("Passport" ,(srange 1 6))
					   ("Passenger List" ,(srange 1 6))
					   ("Landing Gear" ,(srange 1 6))))))
		("TnT" ,(cons `("Start Zone" (("Start Zone" ,(srange 1 8))))
			      (map (lambda (book-n)
				     `(,(string-append "Book " (number->string book-n))
				       ,(append (map (lambda (discovery-n)
						       `(,(string-append "Discovery " (number->string discovery-n)) ,(map (lambda (e) (number->string e)) (range 1 8))))
						     (range 1 9))
						(map (lambda (silver-n)
						       `(,(string-append "Silver " (number->string silver-n)) ("1")))
						     (range 1 9))
						(map (lambda (gold-n)
						       `(,(string-append "Gold " (number->string gold-n)) ("1" "2")))
						     (range 1 9)))))
				   (range 1 5))))
                ("Trek" (("none" (("none" ("none"))))))
                ("Journey" (("none" (("none" ("none"))))))
                 ))
