;;;; ktr-utils.import.scm - GENERATED BY CHICKEN 4.8.0 -*- Scheme -*-

(eval '(import scheme chicken srfi-19 srfi-1))
(##sys#register-compiled-module
  'ktr-utils
  (list)
  '((week-start . ktr-utils#week-start)
    (week-end . ktr-utils#week-end)
    (todays-mm . ktr-utils#todays-mm)
    (todays-dd . ktr-utils#todays-dd)
    (todays-yy . ktr-utils#todays-yy)
    (todays-yyyy . ktr-utils#todays-yyyy)
    (clear-date-time . ktr-utils#clear-date-time)
    (date-as-year . ktr-utils#date-as-year)
    (in-week? . ktr-utils#in-week?)
    (day/month-between? . ktr-utils#day/month-between?)
    (date-year+ . ktr-utils#date-year+)
    (date-year- . ktr-utils#date-year-))
  (list)
  (list))

;; END OF FILE
